name: Remove Label

on: workflow_dispatch

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(CVE-2021, '/remove-labels') }}
        with:
          labels: security vulnerability
